### ISSUE TITLE
casapy tarball missing

### ISSUE THREAD

**Issue by ifornax** [aardk/jupyter-casa#1]
Hi ,

Thanks for this awesome tool. 

I am trying to build the jupyter-casa and getting this error message:

Step 5/14 : ADD casadeps.tar.bz2 casa-4.7.tar.bz2 casa-data.tar.bz2 casa-patch.tar.bz2 /usr/local/
ADD failed: stat /var/lib/docker/tmp/docker-builder411330312/casadeps.tar.bz2: no such file or directory

Thanks for your help

**Comment by aardk** [comment]
Hi Nadeem,

Those files are to big for github, and there is not much value in building
the Docker
from scatch over just pulling it from dockerhub.

But the missing files can be downloaded from here:
ftp://ftp.astron.nl/outgoing/jive/keimpema/

Just put the files in the same directory as the Dockerfile and it should
build just fine.

Regards, Aard.
