### ISSUE TITLE
Error running tclean

### ISSUE THREAD

**Issue by cosmoJFH** [aardk/jupyter-casa#7]
Hi,

I'd like to thank you for creating this notebook. I've compile the project from scratch by myself. The problem is the following: when I execute tclean from the notebook I've got the following error. Do you know what could I do in order to solve it?

process 13: arguments to dbus_message_iter_open_container() were incorrect, assertion "(type == DBUS_TYPE_STRUCT && contained_signature == NULL) || (type == DBUS_TYPE_DICT_ENTRY && contained_signature == NULL) || (type == DBUS_TYPE_VARIANT && contained_signature != NULL) || (type == DBUS_TYPE_ARRAY && contained_signature != NULL)" failed in file ../../dbus/dbus-message.c line 2905.
This is normally a bug in some application using the D-Bus library.
process 13: dbus message iterator looks uninitialized or corrupted
process 13: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2699.
This is normally a bug in some application using the D-Bus library.
process 13: dbus message iterator looks uninitialized or corrupted
process 13: arguments to dbus_message_iter_open_container() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2894.
This is normally a bug in some application using the D-Bus library.
process 13: dbus message iterator looks uninitialized or corrupted
process 13: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2699.
This is normally a bug in some application using the D-Bus library.
process 13: dbus message iterator looks uninitialized or corrupted
process 13: arguments to dbus_message_iter_close_container() were incorrect, assertion "_dbus_message_iter_append_check (real)" failed in file ../../dbus/dbus-message.c line 2961.
This is normally a bug in some application using the D-Bus library.
process 13: dbus message iterator looks uninitialized or corrupted

**Comment by aardk** [comment]
Hi,

I assume that with compile from scratch you mean, building CASA manually and not building the Docker / Singularity images yourself. 

Which OS  and version of CASA are you using? The code was tested under ubuntu 16.04 and casa 5.1.1. 

Do you have all the packages installed which are listed in Singularity / Docker files?
